language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - rey.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- openssl aes-256-cbc -K $encrypted_291f81b268a7_key -iv $encrypted_291f81b268a7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/service-deploy.sh dev $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash scripts/service-deploy.sh master $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: GocVML4pyEpKSZ64nAHVGfriKScCVgnWT6ijjucmHxHdLDJiidiksm6zXlTKYufKs3hL2p62XsAk2bgizt7she1bLoS9tAhOZzXfu0rRlWpZ3OkSIF1I5tFaADIOxDVNaN67xTBQALGBujiLinArjCANhld09x2Gy17Wi7/xHRh4WrPEJ5Q028rja4kjw3AOakVBiepsLY8m9oXgU8YZ40UwiaB7AUsj03kcrJ6xvk4AJUHC4I3nMoZczcI+wB3eyeLpJEmM/6s9sqwvS9q39o3KDX0j2hdciW3OTXji5l3xyf6cKzP6vHAQiR0F4KUlrom93mRVS1mEtzJK+Xe0ExqhwjiGeyzwgFZol+c3UTHDy7425Ha+q1+Q4TDhyFzO+3CEM+bGIR5nIMHVIQmJC7yuUXYSGKDphQdoBYd1Um5o+Vjekfuo9ZBe8e6UE+JiplMaSBCuDSIG2glHTG8VrDU22Iz8a10bXeBd/74yKzxJzpdD9MLxJ7ObF0KzU03QYnMbKbtk+V/1Jxw4I2tDBGEK8XxAnF8Vh1rp4d/jTwL2akaf0gUvqHGp+mllIKKsA0MWYdQmuGM2+DbTRzy7jD62kfM0AhcXgOAcPE4wotsN4ZSLFZVU5OqOzy9533SzkX2xltETncDtkI/2zzzO/XhLEDgxVR5jPVBEoEaEA6k=
